name: Node.js CI and Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install server dependencies
        run: cd server && yarn

      - name: Install client dependencies
        run: cd client && yarn

      - name: Build client
        run: cd client && yarn build

      - name: Run client tests
        run: cd client && yarn test

      - name: Run server tests
        run: cd server && yarn test

      - name: Deploy to _work directory
        run: |
          # Copy your built application to a directory that will be saved as an artifact
          mkdir -p ${{ runner.workspace }}/_work
          cp -r client/dist ${{ runner.workspace }}/_work/client
          cp -r server ${{ runner.workspace }}/_work/server

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ${{ runner.workspace }}/_work

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: website
          path: ${{ runner.workspace }}/_work

      - name: Deploy to Web Server
        run: |
          # You can deploy your website from the _work directory here
          # For example, you can use a tool like rsync or SCP to copy the files to your web server
          # Make sure you set up appropriate credentials and paths for your deployment

