name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Run client tests
        run: cd client && yarn test

      - name: Run server tests
        run: cd ../server && yarn test
