name: Node.js CI and Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install server dependencies
        run: cd server && yarn

      - name: Install client dependencies
        run: cd client && yarn

      - name: Build client
        run: cd client && yarn build

      - name: Run client tests
        run: cd client && yarn test

      - name: Run server tests
        run: cd server && yarn test
