name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install server dependencies
        working-directory: ../../server
        run: yarn

      - name: Install client dependencies
        working-directory: ../../client
        run: yarn

      - name: Build client
        working-directory: ../../client
        run: yarn build

      - name: Run client tests
        working-directory: ../../client
        run: yarn test

      - name: Run server tests
        working-directory: ../../server/
        run: yarn test
